ALTER TABLE artykuly  ALTER cd DROP DEFAULT;
ALTER TABLE ogloszenia  ALTER cd DROP DEFAULT;
ALTER TABLE oferty  ALTER date DROP DEFAULT;
ALTER TABLE galeria  ALTER cd DROP DEFAULT;
ALTER TABLE ksiega  ALTER cd DROP DEFAULT;
ALTER TABLE zyczenia  ALTER cd DROP DEFAULT;

alter table aktywacja ENGINE = InnoDB;
alter table artykuly ENGINE = InnoDB;
alter table comments ENGINE = InnoDB;
alter table galeria ENGINE = InnoDB;
alter table galeria_dzialy ENGINE = InnoDB;
alter table ksiega ENGINE = InnoDB;
alter table oferty ENGINE = InnoDB;
alter table ogloszenia ENGINE = InnoDB;
alter table pks_bus ENGINE = InnoDB;
alter table promotor_articles ENGINE = InnoDB;
alter table promotor_photos ENGINE = InnoDB;
alter table users ENGINE = InnoDB;
alter table zyczenia ENGINE = InnoDB;